<?php
require_once 'includes/functions.php';
requireLogin();


$userId = $_SESSION['user_id'];

// Handle form submission to save the layout
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $headerHtml = $_POST['email_header'];
    $footerHtml = $_POST['email_footer'];
    
    $stmt = $pdo->prepare("UPDATE users SET email_header_html = :header, email_footer_html = :footer WHERE id = :user_id");
    $stmt->execute(['header' => $headerHtml, 'footer' => $footerHtml, 'user_id' => $userId]);
    
    $_SESSION['message'] = "Email layout and signature updated successfully.";
    $_SESSION['message_type'] = "success";
    header("Location: email_layout_settings.php");
    exit();
}

// Fetch the user's current layout
$stmt = $pdo->prepare("SELECT email_header_html, email_footer_html FROM users WHERE id = ?");
$stmt->execute([$userId]);
$layout = $stmt->fetch();
$currentHeader = $layout['email_header_html'] ?? '<h2>EOD REPORT</h2><p><b>From:</b> {username}</p>';
$currentFooter = $layout['email_footer_html'] ?? '<p><i>This email was generated by VirtualOplossing TimeTracker.</i></p>';
require_once 'includes/header.php'; 
?>

<!-- Include TinyMCE. Replace with your actual API key. -->
<script src="https://cdn.tiny.cloud/1/n0wu92kefc4epvtdbx3gtl1yfw5oykhgc341ncwvosakbjdz/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
  // Initialize both editors on the page
  tinymce.init({
    selector: 'textarea.rich-text-editor', // Use a class to target both
    height: 350,
    menubar: 'edit view insert format tools table help',
    plugins: 'preview importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap pagebreak nonbreaking anchor insertdatetime advlist lists wordcount help charmap quickbars emoticons',
    toolbar: 'undo redo | bold italic underline strikethrough | fontfamily fontsize blocks | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | table image link | preview fullscreen',
  });
</script>

<h1><i class="fas fa-palette"></i> Email Layout & Signature</h1>
<p>Design the header and footer that will automatically wrap every EOD report email you send.</p>

<div class="card" style="padding: 25px; margin-top: 20px;">
    <form action="email_layout_settings.php" method="POST">
        <div class="form-group">
            <label for="email_header"><h3>Email Header</h3></label>
            <textarea name="email_header" class="rich-text-editor"><?= htmlspecialchars($currentHeader) ?></textarea>
        </div>

        <div class="form-group" style="margin-top: 30px;">
            <label for="email_footer"><h3>Email Footer / Signature</h3></label>
            <textarea name="email_footer" class="rich-text-editor"><?= htmlspecialchars($currentFooter) ?></textarea>
            <small>You can use the placeholder <code>{username}</code> in both the header and footer.</small>
        </div>
        
        <div style="margin-top: 25px;">
            <button type="submit" class="button button-primary"><i class="fas fa-save"></i> Save Layout</button>
        </div>
    </form>
</div>

<?php require_once 'includes/footer.php'; ?>